# Configuration file for running the test suite. Results typically at http://travis-ci.org/backdrop/backdrop
language: php
sudo: required
dist: precise
group: legacy
php:
  - 5.3
  - 7.0

before_script:
  # Install Apache and FastCGI extension to connect to PHP-FPM.
  - sudo apt-get update > /dev/null
  - sudo apt-get install apache2 libapache2-mod-fastcgi > /dev/null
  - sudo a2enmod rewrite actions fastcgi alias
  - sudo cp -f travis-ci/vhost.conf /etc/apache2/sites-available/default
  - sudo apachectl restart

  # Start PHP-FPM. There is no process manager available to start PHP-FPM on
  # Travis CI currently, so we have to locate and enable it manually.
  - sudo cp travis-ci/php-fpm.conf $HOME/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - $HOME/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm

  # Disable XDebug to speed up execution.
  - phpenv config-rm xdebug.ini

  # Import the PHP configuration.
  - phpenv config-add travis-ci/php.ini

  # Create a RAM disk for MySQL to improve performance.
  - sudo mkdir /mnt/ramdisk
  - sudo mount -t tmpfs -o size=1024m tmpfs /mnt/ramdisk
  - sudo stop mysql
  - sudo mv /var/lib/mysql /mnt/ramdisk
  - sudo ln -s /mnt/ramdisk/mysql /var/lib/mysql
  - sudo start mysql

  # Set MySQL configuration and create the database.
  - mysql -e 'SET GLOBAL wait_timeout = 5400;'
  - mysql -e 'create database test;'

  - cd /var/www
  - wget https://ftp.drupal.org/files/projects/drupal-7.50.tar.gz
  - tar -xzpf drupal-7.50.tar.gz
  - mv drupal-7.50/* ./
  - mv drupal-7.50/.htaccess ./
  - rm -f drupal-7.50
  # Install Backdrop with the installation script.
  - chmod a+w . settings.php
  - ./core/scripts/install.sh --db-url=mysql://travis:@127.0.0.1/test
  - chmod go-w . settings.php
script: env
after_failure:
  - echo "Failures detected. Outputing additional logs:"
  - sudo cat /var/log/apache2/error.log
  - sudo cat /var/log/mysql/error.log